### ISSUE TITLE
Change name of repo to groundmotion-workspace?

### ISSUE THREAD

**Issue by baagaard-usgs** [usgs/groundmotion-database#30]
Should we rename this repo groundmotion-workspace?

I think our vision for the functionality of this repo is that it provides a high-level interface for ground-motion processing via a common workspace. "database" seems a bit of a misnomer because it suggests queries for data, etc, which are not the central focus of the repo.

**Comment by emthompson-usgs** [comment]
I've discussed with the other contributors to this project and we are all in agreement that this is a good idea. I'll make the change now.
